### ISSUE TITLE
Enrober should add calico annotations on all deployments.

### ISSUE THREAD

**Issue by jbowen93** [30x/enrober#15]

**Comment by jbowen93** [comment]
Calico annotations are listed as deprecated. 
https://github.com/projectcalico/calico-containers/blob/v0.19.0/docs/cni/kubernetes/AnnotationPolicy.md#deprecated
We should discuss next steps, suggested replacement is here:
https://github.com/caseydavenport/kubernetes/blob/network-policy/docs/admin/network-policy.md#network-policy-in-kubernetes but is currently in Alpha and set to be Beta in 1.3.

**Comment by madhurranjan** [comment]
We're not moving to the latest version of calico till the next k8s release. So existing set of annotations would prevail in 1.2.X

**Comment by jbowen93** [comment]
Sounds good. I'll add annotations per the older guide.

**Comment by jbowen93** [comment]
What are all of the calico policies that should be by default added to created pods?

**Comment by madhurranjan** [comment]
1. Every pod by default has a namespace_<name of namespace> rule that's added. This would allow other pods in the same namespace to talk to the pod that is being launched
2. In addition we need to add a new rule that has this : calicoctl profile <profile_name> rule add inbound allow from tag namespace_<namespace where ingress is setup>. This has to be a manual calicoctl command because the current version doesn't support this via apis. However, the good part is if there are multiple invocations of the same, its idempotent.

**Comment by jbowen93** [comment]
So for the number 2 that can't be done through an annotation? So the only annotation that needs to be added is allowing traffic from other pods in the same namespace?

**Comment by madhurranjan** [comment]
Yes 2 can't be done using an annotation unfortunately in the current version. With network policies we should be able to do that. Only extra annotation is the one from nginx-ingress to all pods.

**Comment by jbowen93** [comment]
According to [this](https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/AnnotationPolicy.md#behavior) pods are by default namespace isolated. So we just need to allow created pods to be accessible by services running in the `apigee-admin` namespace where the router and deployment services run. Please correct me if I'm mistaken.

**Comment by jbowen93** [comment]
Closing this as I don't believe it fits under `enrober`. Issue is continued in [#71](https://github.com/30x/project-management/issues/71)
