### ISSUE TITLE
Review cleanup/stagnant resources

### ISSUE THREAD

**Issue by whitlockjc** [30x/enrober#56]
The nature of deployments is that when you alter them, the old `ReplicaSet` is scaled to `0` but never deleted.  This means that the old `ReplicaSet` will live forever and take up `etcd` resources.  That being said, we might want to come up with a plan that allows for rollback and other versioning without growing infinitely.

Here is a good piece of information: http://kubernetes.io/docs/user-guide/deployments/#revision-history-limit

**Comment by jbowen93** [comment]
For enrober we should probably just pick a reasonable default and come back to this if it's causing issues. I'm thinking 5 revisions should be fine, especially since we're deploying relatively simple reproducible pod template specs. With regards to our own deployments we may want to add a line to limit to something like 5 revisions as currently there are about 20 replica sets for enrober on E2E.

**Comment by whitlockjc** [comment]
Yeah, I'm not sure we have to solve this now.  I just wanted to create an issue to track it.  I think will likely be dictated based on the features we provide around it, like rolling back and such.  Maybe @mpnally can respond.

**Comment by jbowen93** [comment]
This was solved with PR #59
