### ISSUE TITLE
Remove ability to POST environment

### ISSUE THREAD

**Issue by jbowen93** [30x/enrober#86]
We no longer want to create environments independently. Instead when a deployment is created there should be a check to see if that environment already exists. If it doesn't then it will be created. 

This removes the POST functionality on `/environments`

**Comment by jbowen93** [comment]
First pass of this will be enabling a POST on `/environments/{org}:{env}/deployments` to create a properly named environment if it doesn't already exit.

**Comment by jbowen93** [comment]
@mpnally @whitlockjc Do we have an answer for how we want this feature implemented?
https://github.com/30x/enrober/blob/issue86/pkg/server/server.go#L426

**Comment by whitlockjc** [comment]
This is a good question.  Until you have a proxy created, you don't know which hosts are available.  Since Apigee edge uses the proxy name in its pattern for composing the `.apigee.net` host name, we can't compute it.  For the virtual hosts _(Apigee term)_, we could take the same approach `apigee-tool` takes by accepting the virtual host name.  Maybe we'll need to discuss this tomorrow in the parking lot.
